version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"  # Replace with your application port
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres